name: Deploy

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4  # Update to v4 of setup-node
        with:
          node-version: '14'  # Specify Node.js version as needed

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4  # Update to v4 of upload-artifact
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Adjust branch name as needed

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4  # Update to v4 of download-artifact
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
